/** Shared core perpetual symbols — keep Binance & OKX in sync.
 *  ~30 high-liquidity USDT perps (by contract liquidity, not spot market-cap top 100).
 */
export const CORE_BASES = [
  "BTC",
  "ETH",
  "SOL",
  "BNB",
  "XRP",
  "DOGE",
  "ADA",
  "AVAX",
  "LINK",
  "DOT",
  "MATIC",
  "LTC",
  "ATOM",
  "NEAR",
  "APT",
  "ARB",
  "OP",
  "SUI",
  "INJ",
  "FIL",
  "UNI",
  "AAVE",
  "PEPE",
  "WIF",
  "TIA",
  "SEI",
  "TON",
  "TRX",
  "BCH",
  "ETC",
] as const;

export const CORE_SYMBOLS = CORE_BASES.map((base) => `${base}USDT`);

export const ASSET_NAMES: Record<string, string> = {
  BTC: "Bitcoin",
  ETH: "Ethereum",
  SOL: "Solana",
  BNB: "BNB",
  XRP: "XRP",
  DOGE: "Dogecoin",
  ADA: "Cardano",
  AVAX: "Avalanche",
  LINK: "Chainlink",
  DOT: "Polkadot",
  MATIC: "Polygon",
  LTC: "Litecoin",
  ATOM: "Cosmos",
  NEAR: "NEAR",
  APT: "Aptos",
  ARB: "Arbitrum",
  OP: "Optimism",
  SUI: "Sui",
  INJ: "Injective",
  FIL: "Filecoin",
  UNI: "Uniswap",
  AAVE: "Aave",
  PEPE: "Pepe",
  WIF: "dogwifhat",
  TIA: "Celestia",
  SEI: "Sei",
  TON: "Toncoin",
  TRX: "TRON",
  BCH: "Bitcoin Cash",
  ETC: "Ethereum Classic",
};

/** Priority order for progressive / first-paint loading (12–15 檔) */
export const PRIORITY_SYMBOLS = [
  "BTCUSDT",
  "ETHUSDT",
  "SOLUSDT",
  "BNBUSDT",
  "XRPUSDT",
  "DOGEUSDT",
  "ADAUSDT",
  "AVAXUSDT",
  "LINKUSDT",
  "DOTUSDT",
  "SUIUSDT",
  "ARBUSDT",
  "OPUSDT",
  "NEARUSDT",
  "APTUSDT",
] as const;
